nums = [2, 1, 3, 9, 4]
print(nums)
print(nums[0])
print(nums[4])
print(nums[2:])
print(nums[-1])
print(nums[-5])
names = ['nithin, goud, bathini']
print(names)
values = [2.5, 'nithin', 25]
print(values)
mil = [nums, names]
print(mil)
nums.append(5)
print(nums)
nums.insert(2, 55)
print(nums)
nums.remove(4)
print(nums)
nums.pop(2)
print(nums)
nums.pop()
print(nums)
del nums[2:]
print(nums)
nums.extend([29, 12, 14, 36])
print(nums)
print(max(nums))
print(min(nums))
print(sum(nums))
nums.sort()
print(nums)
